name: Assignment Auto-Grader

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  grade-assignment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore demo/demo.sln

    - name: Build
      run: dotnet build demo/demo.sln --no-restore --configuration Release

    - name: Run program and check output
      run: |
        echo "Running the program..."
        output=$(dotnet run --project demo/demo.csproj --configuration Release)
        echo "Program output: '$output'"

        # Check if output contains "Hello, World!" (with exclamation mark)
        if [[ "$output" == *"Hello, World!"* ]]; then
          echo "✅ SUCCESS: Program outputs 'Hello, World!' correctly!"
          echo "🎉 Assignment completed successfully!"
        else
          echo "❌ FAILURE: Program output does not contain 'Hello, World!' with exclamation mark"
          echo "Expected: Hello, World!"
          echo "Got: $output"
          echo ""
          echo "💡 Hint: Make sure to add an exclamation mark (!) to the end of 'Hello, World' in Program.cs"
          exit 1
        fi
