name: .NET CI

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore dependencies
      run: dotnet restore demo/demo.sln
      
    - name: Build
      run: dotnet build demo/demo.sln --no-restore --configuration Release
      
    - name: Test
      run: dotnet test demo/demo.sln --no-build --configuration Release --verbosity normal
      
    - name: Publish
      run: dotnet publish demo/demo.csproj --no-build --configuration Release --output ./publish
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish

  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore demo/demo.sln
      
    - name: Build
      run: dotnet build demo/demo.sln --no-restore --configuration Release
      
    - name: Test
      run: dotnet test demo/demo.sln --no-build --configuration Release --verbosity normal

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore demo/demo.sln
      
    - name: Build
      run: dotnet build demo/demo.sln --no-restore --configuration Release
      
    - name: Test
      run: dotnet test demo/demo.sln --no-build --configuration Release --verbosity normal
